kind: pipeline
type: docker
name: linux

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.14
  commands:
  - sh scripts/build.sh

- name: publish_amd64
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: hwbarkdull/drone-runner-macstadium
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: publish_arm
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: hwbarkdull/drone-runner-macstadium
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: docker/Dockerfile.linux.arm
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: publish_arm64
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: hwbarkdull/drone-runner-macstadium
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: docker/Dockerfile.linux.arm64
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: manifest
  image: plugins/manifest
  settings:
    spec: docker/manifest.tmpl
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: DOCKER_PASSWORD
    username:
      from_secret: DOCKER_USERNAME
  when:
    ref:
    - refs/heads/master
    - refs/tags/*
